name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  formatter:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant write permissions to the GITHUB_TOKEN
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Replace with your desired Python version

      # Install Black
      - name: Install Black
        run: pip install black

      # Run Black to format the code
      - name: Run Black
        run: black .

      # Check if there are any changes after formatting
      - name: Check for changes
        id: changes
        run: |
          git diff --exit-code || echo "::set-output name=changes::true"

      # Commit changes if there are any
      - name: Commit auto-fixes
        if: steps.changes.outputs.changes == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Apply Black formatting [skip ci]" || echo "No changes to commit"
          git push